source 'https://rubygems.org'

gem 'github-pages'
gem 'jekyll-sitemap'     # 自动生成sitemap
gem 'jekyll-feed'        # 生成RSS订阅
gem 'jekyll-seo-tag'     # SEO优化
gem 'jekyll-paginate'    # 分页功能

group :development do
  gem 'webrick'          # Ruby 3.0以上版本需要
 end